Allow submitting forms
nbeijerbacht/InfoTeams pull request #55
Opened 2022-10-13 10:18 UTC by BondarencoM

2022-10-13 11:30 UTC, phantorios approved these changes

2022-10-13 11:30 UTC, phantorios commented on FormService/Controllers/FormController.cs
> +        var result = rederer.Render(formData);
rederer to renderer maybe better?

2022-10-13 11:33 UTC, nbeijerbacht requested changes

2022-10-13 11:33 UTC, nbeijerbacht commented on FormService/Logic/Field Types/NumericFieldRenderer.cs
> +        var (min, max) = (e.field.min_numeric_value, e.field.max_numeric_value);
Maybe we should find a better place to validate these submited values

2022-10-13 11:33 UTC, nbeijerbacht commented on FormService/Logic/IgnoreRenderer.cs
>              "page_break",
Maybe its a good time to remove the ignore

2022-10-13 11:33 UTC, nbeijerbacht commented on InfoTeamsExperiment/MessageHandlers/SubmitFormMessageHandler.cs
> +public class SubmitFormMessageHandler : ITeamsMessageHandler
Add some code comments to explain what is happening here.

2022-10-16 19:23 UTC, BondarencoM commented on FormService/Logic/Field Types/NumericFieldRenderer.cs
> +        var (min, max) = (e.field.min_numeric_value, e.field.max_numeric_value);
This is not really validation, it just sets the properties of the input field. It is a lot like setting the type.
Additionally this is by far the most convenient place to put it.

2022-10-16 19:26 UTC, BondarencoM commented on FormService/Logic/IgnoreRenderer.cs
>              "page_break",
I would keep it for a while longer. It may be useful when developing fields. Although it's guaranteed to cause problems at some point, so keep an eye on it.

2022-10-17 08:25 UTC, BondarencoM commented on FormService/Controllers/FormController.cs
> +        var result = rederer.Render(formData);
Fixed

2022-10-17 09:16 UTC, BondarencoM commented on FormService/Logic/Field Types/NumericFieldRenderer.cs
> +        var (min, max) = (e.field.min_numeric_value, e.field.max_numeric_value);
This is not really validation, it's setting the properties of the input field. It's a lot like setting the data type.
Also this is the most convenient place to set these parameters.

2022-10-17 09:16 UTC, BondarencoM commented on FormService/Logic/IgnoreRenderer.cs
>              "page_break",
I think it can be useful for a while longer, especially when developing all these fields together. But it can cause problems so make sure nobody commits anything bad there.

2022-10-17 09:32 UTC, nbeijerbacht approved these changes

2022-10-17 09:32 UTC, merged